name: "recruit-center"
version: "1.0.0"
env: "development"
port: 9850
host: "localhost"

# 数据库配置
db:
  host: "192.168.2.185"
  port: 5432
  username: "pgtest"
  password: "123456"
  database: "testdb"


# 日志配置
log:
  level: "info"
  filename: "logs/recruit-center.log"
  maxsize: 100 # MB
  maxage: 30 # 天
  maxbackups: 10 # 保留文件个数

# OSS配置
oss:
  endpoint: "your-oss-endpoint"
  access_key_id: "your-access-key"
  secret_access_key: "your-secret-key"
  use_ssl: true

# 文件上传配置
file_upload:
  max_size: 10485760 # 10MB in bytes
  max_files: 5
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "application/pdf"
    - "application/msword"
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
  allowed_exts:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".pdf"
    - ".doc"
    - ".docx"

# AI服务配置
ai:
  baseURL: https://api.guijilife.com/v1
  apiKey: your-api-key-here
  modelName: gpt-4
  timeout: 30s
  maxRetries: 3
jwt:
  secret: abcd123456