// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/applies": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "分页获取所有职位申请记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位申请"
                ],
                "summary": "获取申请列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码 (默认值: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量 (默认值: 10)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PageResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.JobApply"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的职位申请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位申请"
                ],
                "summary": "创建职位申请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "申请信息",
                        "name": "apply",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.JobApply"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.JobApply"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/applies/{id}": {
            "get": {
                "description": "获取指定ID的职位申请详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位申请"
                ],
                "summary": "获取申请详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "申请ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.JobApply"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/companies/{companyId}/jobs": {
            "get": {
                "description": "获取指定公司发布的所有职位",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位"
                ],
                "summary": "获取公司职位",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公司ID",
                        "name": "companyId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Job"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "公司不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs": {
            "get": {
                "description": "分页获取职位列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位管理"
                ],
                "summary": "获取职位列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.PageResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Job"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建新职位,需要提供职位相关信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位"
                ],
                "summary": "创建职位",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "职位创建请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Job"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/expired": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有已过期的职位列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位"
                ],
                "summary": "获取已过期职位",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Job"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/search": {
            "get": {
                "description": "根据关键词搜索职位信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位"
                ],
                "summary": "关键词搜索职位",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Job"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/search/condition": {
            "post": {
                "description": "根据多个条件筛选职位",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位"
                ],
                "summary": "多条件搜索职位",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "description": "搜索条件",
                        "name": "conditions",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Job"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/{id}": {
            "get": {
                "description": "获取指定ID的职位详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位管理"
                ],
                "summary": "获取职位详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "职位ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Job"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新指定ID的职位信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位"
                ],
                "summary": "更新职位",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "职位ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "职位更新请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Job"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "职位不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除指定ID的职位",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位"
                ],
                "summary": "删除职位",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "职位ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "职位不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/{id}/status": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新指定职位的状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "职位"
                ],
                "summary": "更新职位状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer JWT",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "职位ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            0,
                            1,
                            2
                        ],
                        "type": "integer",
                        "description": "状态值",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "职位不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/resumes": {
            "post": {
                "description": "创建用户简历信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "简历管理"
                ],
                "summary": "创建简历",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "简历信息",
                        "name": "resume",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateResumeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Resume"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/resumes/access-status": {
            "put": {
                "description": "更新用户简历的访问状态（公开/隐藏）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "简历管理"
                ],
                "summary": "更新简历访问状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "访问状态",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateResumeStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/resumes/my": {
            "get": {
                "description": "获取当前登录用户的简历信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "简历管理"
                ],
                "summary": "获取用户简历",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Resume"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/resumes/upload": {
            "post": {
                "description": "上传用户简历文件",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "简历管理"
                ],
                "summary": "上传简历文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "简历文件",
                        "name": "resume",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/resumes/working-status": {
            "put": {
                "description": "更新用户简历的工作状态（在职/离职）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "简历管理"
                ],
                "summary": "更新简历工作状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "工作状态",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateResumeStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "enums.JobType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "JobTypeFullTime": "全职",
                "JobTypeIntern": "实习",
                "JobTypePartTime": "兼职"
            },
            "x-enum-descriptions": [
                "全职",
                "兼职",
                "实习"
            ],
            "x-enum-varnames": [
                "JobTypeFullTime",
                "JobTypePartTime",
                "JobTypeIntern"
            ]
        },
        "errors.ErrorCode": {
            "type": "integer",
            "enum": [
                200,
                400,
                401,
                403,
                404,
                405,
                409,
                429,
                422,
                500,
                503,
                1001,
                1002,
                1003,
                2001,
                2002,
                2003,
                3001,
                3002,
                4001,
                4002,
                4003,
                4004
            ],
            "x-enum-comments": {
                "BadRequest": "请求参数错误",
                "CompanyInactive": "公司未激活",
                "CompanyNotFound": "公司不存在",
                "Conflict": "资源冲突",
                "FileTooLarge": "文件过大",
                "FileTypeNotAllowed": "文件类型不允许",
                "Forbidden": "禁止访问",
                "InternalServerError": "服务器内部错误",
                "InvalidFileFormat": "无效的文件格式",
                "InvalidParams": "无效的请求参数",
                "JobAlreadyApplied": "已经申请过该职位",
                "JobExpired": "职位已过期",
                "JobNotFound": "职位不存在",
                "MethodNotAllowed": "方法不允许",
                "NotFound": "资源不存在",
                "PasswordIncorrect": "密码错误",
                "ServiceUnavailable": "服务不可用",
                "TooManyFiles": "文件数量超过限制",
                "TooManyRequests": "请求过多",
                "Unauthorized": "未授权",
                "UserAlreadyExists": "用户已存在",
                "UserNotFound": "用户不存在"
            },
            "x-enum-descriptions": [
                "",
                "请求参数错误",
                "未授权",
                "禁止访问",
                "资源不存在",
                "方法不允许",
                "资源冲突",
                "请求过多",
                "无效的请求参数",
                "服务器内部错误",
                "服务不可用",
                "用户不存在",
                "用户已存在",
                "密码错误",
                "职位不存在",
                "职位已过期",
                "已经申请过该职位",
                "公司不存在",
                "公司未激活",
                "文件过大",
                "文件类型不允许",
                "无效的文件格式",
                "文件数量超过限制"
            ],
            "x-enum-varnames": [
                "Success",
                "BadRequest",
                "Unauthorized",
                "Forbidden",
                "NotFound",
                "MethodNotAllowed",
                "Conflict",
                "TooManyRequests",
                "InvalidParams",
                "InternalServerError",
                "ServiceUnavailable",
                "UserNotFound",
                "UserAlreadyExists",
                "PasswordIncorrect",
                "JobNotFound",
                "JobExpired",
                "JobAlreadyApplied",
                "CompanyNotFound",
                "CompanyInactive",
                "FileTooLarge",
                "FileTypeNotAllowed",
                "InvalidFileFormat",
                "TooManyFiles"
            ]
        },
        "model.Education": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "degree": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "major": {
                    "type": "string"
                },
                "resumeId": {
                    "type": "integer"
                },
                "school": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Job": {
            "type": "object",
            "properties": {
                "applyCount": {
                    "description": "申请次数",
                    "type": "integer"
                },
                "companyId": {
                    "type": "integer"
                },
                "createTime": {
                    "type": "string"
                },
                "deleteStatus": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "jobBenefit": {
                    "type": "string"
                },
                "jobCategory": {
                    "type": "string"
                },
                "jobContact": {
                    "type": "string"
                },
                "jobDescribe": {
                    "type": "string"
                },
                "jobEducation": {
                    "type": "string"
                },
                "jobExperience": {
                    "type": "string"
                },
                "jobExpireTime": {
                    "type": "string"
                },
                "jobLocation": {
                    "type": "string"
                },
                "jobSalary": {
                    "type": "string"
                },
                "jobSkill": {
                    "type": "string"
                },
                "jobSource": {
                    "type": "string"
                },
                "jobType": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "description": "优先级",
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "tags": {
                    "description": "职位标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updateTime": {
                    "type": "string"
                },
                "viewCount": {
                    "description": "添加新的字段和方法",
                    "type": "integer"
                }
            }
        },
        "model.JobApply": {
            "type": "object",
            "properties": {
                "applyProgress": {
                    "type": "string"
                },
                "applyTime": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jobId": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "model.Project": {
            "type": "object",
            "properties": {
                "achievement": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "resumeId": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "technology": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Resume": {
            "type": "object",
            "properties": {
                "accessStatus": {
                    "description": "1: 隐藏, 2: 公开",
                    "type": "integer"
                },
                "attachments": {
                    "description": "新增附件关联",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ResumeAttachment"
                    }
                },
                "avatar": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "educations": {
                    "description": "关联",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Education"
                    }
                },
                "email": {
                    "type": "string"
                },
                "expectedCity": {
                    "type": "string"
                },
                "expectedJob": {
                    "type": "string"
                },
                "experience": {
                    "type": "integer"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "introduction": {
                    "type": "string"
                },
                "jobStatus": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Project"
                    }
                },
                "skills": {
                    "type": "string"
                },
                "status": {
                    "description": "1: 正常, 0: 删除",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "workExperiences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.WorkExperience"
                    }
                },
                "workingStatus": {
                    "description": "1: 在职, 2: 离职",
                    "type": "integer"
                }
            }
        },
        "model.ResumeAttachment": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "fileName": {
                    "description": "文件名",
                    "type": "string"
                },
                "fileSize": {
                    "description": "文件大小(字节)",
                    "type": "integer"
                },
                "fileType": {
                    "description": "文件类型(如: pdf, doc, docx等)",
                    "type": "string"
                },
                "fileUrl": {
                    "description": "文件URL",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "resumeId": {
                    "type": "integer"
                },
                "status": {
                    "description": "状态(1: 正常, 0: 删除)",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.WorkExperience": {
            "type": "object",
            "properties": {
                "achievement": {
                    "type": "string"
                },
                "companyName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "position": {
                    "type": "string"
                },
                "resumeId": {
                    "type": "integer"
                },
                "startTime": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "request.CreateJobRequest": {
            "type": "object"
        },
        "request.CreateResumeRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "phone"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "educations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EducationRequest"
                    }
                },
                "email": {
                    "type": "string"
                },
                "expectedCity": {
                    "type": "string"
                },
                "expectedJob": {
                    "type": "string"
                },
                "experience": {
                    "type": "integer"
                },
                "gender": {
                    "type": "integer"
                },
                "introduction": {
                    "type": "string"
                },
                "jobStatus": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.ProjectRequest"
                    }
                },
                "skills": {
                    "type": "string"
                },
                "workExperiences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.WorkExperienceRequest"
                    }
                }
            }
        },
        "request.EducationRequest": {
            "type": "object",
            "required": [
                "school"
            ],
            "properties": {
                "degree": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "school": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                }
            }
        },
        "request.JobApply": {
            "type": "object",
            "properties": {
                "applyProgress": {
                    "description": "改为 applyProgress",
                    "type": "string"
                },
                "applyTime": {
                    "description": "改为 applyTime",
                    "type": "string"
                },
                "createTime": {
                    "description": "改为 createTime",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jobId": {
                    "description": "改为 jobId",
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/request.JobApplyStatus"
                },
                "updateTime": {
                    "description": "改为 updateTime",
                    "type": "string"
                },
                "userId": {
                    "description": "改为 userId",
                    "type": "integer"
                }
            }
        },
        "request.JobApplyStatus": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5
            ],
            "x-enum-comments": {
                "JobApplyStatusAccepted": "已接受",
                "JobApplyStatusInProgress": "进行中",
                "JobApplyStatusPending": "待处理",
                "JobApplyStatusRejected": "已拒绝",
                "JobApplyStatusWithdrawn": "已撤回"
            },
            "x-enum-descriptions": [
                "待处理",
                "进行中",
                "已接受",
                "已拒绝",
                "已撤回"
            ],
            "x-enum-varnames": [
                "JobApplyStatusPending",
                "JobApplyStatusInProgress",
                "JobApplyStatusAccepted",
                "JobApplyStatusRejected",
                "JobApplyStatusWithdrawn"
            ]
        },
        "request.ProjectRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "achievement": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "technology": {
                    "type": "string"
                }
            }
        },
        "request.UpdateJobRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "jobBenefit": {
                    "type": "string",
                    "maxLength": 500
                },
                "jobCategory": {
                    "type": "string",
                    "maxLength": 50
                },
                "jobContact": {
                    "type": "string",
                    "maxLength": 100
                },
                "jobDescribe": {
                    "type": "string",
                    "maxLength": 2000
                },
                "jobEducation": {
                    "type": "string",
                    "maxLength": 50
                },
                "jobExperience": {
                    "type": "string",
                    "maxLength": 50
                },
                "jobExpireTime": {
                    "type": "string"
                },
                "jobLocation": {
                    "type": "string",
                    "maxLength": 200
                },
                "jobSalary": {
                    "type": "string",
                    "maxLength": 50
                },
                "jobSkill": {
                    "type": "string",
                    "maxLength": 500
                },
                "jobSource": {
                    "type": "string",
                    "maxLength": 100
                },
                "jobType": {
                    "$ref": "#/definitions/enums.JobType"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "request.UpdateResumeStatusRequest": {
            "type": "object",
            "required": [
                "resumeId",
                "status"
            ],
            "properties": {
                "resumeId": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                }
            }
        },
        "request.WorkExperienceRequest": {
            "type": "object",
            "required": [
                "companyName"
            ],
            "properties": {
                "achievement": {
                    "type": "string"
                },
                "companyName": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                }
            }
        },
        "response.PageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/errors.ErrorCode"
                        }
                    ]
                },
                "data": {
                    "description": "响应数据"
                },
                "message": {
                    "description": "响应信息",
                    "type": "string"
                },
                "page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/errors.ErrorCode"
                        }
                    ]
                },
                "data": {
                    "description": "响应数据"
                },
                "message": {
                    "description": "响应信息",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "招聘中心 API",
	Description:      "招聘中心系统 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
